# Generated by Django 6.0.6 on 2026-07-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('week_capacity', models.FloatField(default=40, verbose_name='周容量(人时)')),
                ('modules', models.CharField(blank=True, help_text='逗号分隔,如 后端,前端', max_length=128, verbose_name='负责模块')),
                ('active', models.BooleanField(default=True, verbose_name='在职')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
    ]
