# Generated by Django 6.0.6 on 2026-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='迭代')),
                ('start_date', models.DateField(verbose_name='开始日')),
                ('end_date', models.DateField(verbose_name='结束日')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前迭代')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '迭代',
                'verbose_name_plural': '迭代',
                'ordering': ['-start_date'],
            },
        ),
    ]
