# Generated by Django 6.0.6 on 2026-07-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('status', models.CharField(choices=[('backlog', '待评审'), ('scheduled', '排期中'), ('in_progress', '开发中'), ('testing', '测试中'), ('done', '已上线'), ('blocked', '已阻塞'), ('paused', '暂停')], default='backlog', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='P1', max_length=4, verbose_name='优先级')),
                ('module', models.CharField(blank=True, max_length=64, verbose_name='模块')),
                ('progress', models.IntegerField(default=0, verbose_name='进度%')),
                ('est_effort', models.FloatField(default=0, verbose_name='预计工时(h)')),
                ('actual_effort', models.FloatField(default=0, verbose_name='实际工时(h)')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='预计开始')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='预计结束')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sprint', verbose_name='所属迭代')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-created_at'],
            },
        ),
    ]
