# Generated by Django 6.0.6 on 2026-07-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'ordering': ['-date'],
            },
        ),
    ]
