# Generated by Django 6.0.6 on 2026-07-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurndownSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('remaining_effort', models.FloatField(default=0, verbose_name='剩余工时(h)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sprint', verbose_name='迭代')),
            ],
            options={
                'verbose_name': '燃尽图快照',
                'verbose_name_plural': '燃尽图快照',
                'ordering': ['date'],
                'unique_together': {('sprint', 'date')},
            },
        ),
    ]
