# Generated by Django 6.0.6 on 2026-07-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_burndownsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.requirement', verbose_name='父需求'),
        ),
    ]
