# Generated by Django 6.0.6 on 2026-07-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requirement_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('remaining_effort', models.FloatField(default=0, verbose_name='剩余工时(h)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '每日工时快照',
                'verbose_name_plural': '每日工时快照',
                'ordering': ['-date'],
                'unique_together': {('date', 'member')},
            },
        ),
    ]
