# Generated by Django 6.0.6 on 2026-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_memberdailysnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='assigned_sprint',
        ),
        migrations.DeleteModel(
            name='BurndownSnapshot',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
