# Generated by Django 6.0.6 on 2026-07-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_requirement_assigned_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='版本')),
                ('integration_date', models.DateField(blank=True, null=True, verbose_name='联调日')),
                ('freeze_date', models.DateField(blank=True, null=True, verbose_name='封板日')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='转测日')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='core.version', verbose_name='目标版本'),
        ),
    ]
