# Generated by Django 6.0.6 on 2026-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_version_requirement_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, to='core.requirement', verbose_name='被阻塞于'),
        ),
    ]
