# Generated by Django 6.0.6 on 2026-07-24 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requirement_blocked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='last_status_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='actual_effort',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实际工时(h)'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='est_effort',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='预计工时(h)'),
        ),
    ]
