# Generated by Django 6.0.6 on 2026-07-24 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_requirement_last_status_change_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='从状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='到状态')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.requirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '状态变更日志',
                'verbose_name_plural': '状态变更日志',
                'ordering': ['changed_at'],
            },
        ),
    ]
