# Generated by Django 6.0.6 on 2026-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_requirementstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='kind',
            field=models.CharField(choices=[('feature', '需求'), ('bug', '缺陷')], default='feature', max_length=10, verbose_name='类型'),
        ),
    ]
