# Generated by Django 6.0.6 on 2026-07-24 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_timeentries(apps, schema_editor):
    Requirement = apps.get_model('core', 'Requirement')
    TimeEntry = apps.get_model('core', 'TimeEntry')
    Member = apps.get_model('core', 'Member')
    today = timezone.now().date()
    for r in Requirement.objects.all():
        if r.actual_effort and r.actual_effort > 0:
            TimeEntry.objects.create(requirement=r, member=r.assignee, hours=r.actual_effort,
                                     date=today, note='初始回填')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_requirement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='工时(h)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member', verbose_name='成员')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeentries', to='core.requirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '工时记录',
                'verbose_name_plural': '工时记录',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RunPython(backfill_timeentries, migrations.RunPython.noop),
    ]
