# Generated by Django 6.0.6 on 2026-07-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='阶段(留空=按日期派生)'),
        ),
    ]
