# Generated by Django 6.0.6 on 2026-07-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_version_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='dev_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='投入开始日'),
        ),
        migrations.CreateModel(
            name='VersionMergePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='合入日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_points', to='core.version', verbose_name='版本')),
            ],
            options={
                'verbose_name': '版本合入点',
                'verbose_name_plural': '版本合入点',
                'ordering': ['-date'],
            },
        ),
    ]
