# Generated by Django 6.0.6 on 2026-07-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_version_dev_start_date_versionmergepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmergepoint',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='合入日期'),
        ),
    ]
